//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2dmSharp.Client.Sample
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int buttonRegister = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int textHints = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int textLastMessage = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int textRegistrationId = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int textRegistrationStatus = 2130968576;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			private Layout()
			{
			}
		}
	}
}
